import React, { useState } from 'react';
import { Account } from '../types';
import { 
  FileText, 
  Download, 
  Copy, 
  Check, 
  Ticket, 
  Bell, 
  Printer, 
  Sparkles, 
  ShieldAlert,
  Building2,
  Calendar,
  Layers
} from 'lucide-react';

interface AuditReportStudioProps {
  accounts: Account[];
  selectedAccount?: Account | null;
  onDispatchMcpAction?: (actionType: 'JIRA' | 'SLACK', payload: any) => void;
}

export const AuditReportStudio: React.FC<AuditReportStudioProps> = ({
  accounts,
  selectedAccount,
  onDispatchMcpAction,
}) => {
  const [targetAccountId, setTargetAccountId] = useState<string>(
    selectedAccount ? selectedAccount.account_id : 'ACC-8921-CORP'
  );
  const [reportType, setReportType] = useState<string>('SAR_STR');
  const [investigatorNotes, setInvestigatorNotes] = useState<string>(
    'Behavioral structuring pattern confirmed across 50 outbound wire transfers within a 45-minute window. Immediate account lien authorized under RBI Master Direction Section 38.'
  );
  const [createJiraTicket, setCreateJiraTicket] = useState<boolean>(true);
  const [notifySlack, setNotifySlack] = useState<boolean>(true);
  const [generatedReport, setGeneratedReport] = useState<string | null>(null);
  const [copied, setCopied] = useState<boolean>(false);
  const [dispatchedJira, setDispatchedJira] = useState<string | null>(null);
  const [dispatchedSlack, setDispatchedSlack] = useState<boolean>(false);

  const currentAccount = accounts.find(a => a.account_id === targetAccountId) || accounts[0];

  const handleGenerate = () => {
    const timestamp = new Date().toUTCString();
    const caseId = `SAR-2026-${currentAccount.account_id.replace(/[^0-9]/g, '') || '8921'}`;

    let md = '';

    if (reportType === 'SAR_STR') {
      md = `# SUSPICIOUS ACTIVITY REPORT (SAR) / STR DOSSIER
**CONFIDENTIAL // REGULATORY COMPLIANCE & LAW ENFORCEMENT ONLY**
**Filing Authority:** Financial Intelligence Unit (FIU-IND) / Host Supervisor
**Generated by:** Snowflake CoCo Governed Agent Skill: \`audit_report_generator\`

---

### SECTION 1: ENTITY IDENTIFICATION & SUBJECT PROFILE
- **Internal Case Reference:** \`${caseId}\`
- **Audit Timestamp:** \`${timestamp}\`
- **Target Account Number:** \`${currentAccount.account_id}\`
- **Entity Legal Name:** **${currentAccount.entity_name}**
- **Operating Jurisdiction:** \`${currentAccount.jurisdiction}\`
- **Customer Risk Tier:** **${currentAccount.risk_tier}**
- **Ledger Balance:** \`$${currentAccount.current_balance.toLocaleString('en-US', { minimumFractionDigits: 2 })} USD\`
- **KYC Standing:** \`${currentAccount.kyc_status}\`

---

### SECTION 2: FORENSIC ANOMALY FINDINGS
CoCo Agentic Detection Pipeline flagged the following behavioral breaches:
1. **Smurfing & Structuring Pattern (RULE_AML_04):**
   - 50 consecutive outbound payment hops executed between $9,900 and $9,980.
   - Aggregate sum flagged: **$498,500.00 USD**.
   - Timing: Compressed 45-minute execution window, representing 18.5x the 30-day baseline standard deviation.
   - Counterparty Hub: Offshore non-cooperative beneficiary jurisdiction.
2. **Confidence Metric:** \`96.4%\` via Snowpark ML classification model.

---

### SECTION 3: STATUTORY REGULATORY CITATIONS
Automated Snowflake Cortex Vector Search over regulatory corpus identified the following legal mandates:
- **Authority:** Reserve Bank of India (RBI)
- **Document Title:** Master Direction - Know Your Customer (KYC) Direction, 2016 (Updated 2024)
- **Section / Clause:** Section 38 & Chapter VI (Monitoring of Transactions)
- **Authoritative Text:** *"Any series of integrated cash or wire transactions individually below rupees ten lakhs but integrally connected exceeding threshold in a calendar month must be tagged as suspicious structuring."*
- **Statutory Mandate:** **Mandatory filing of STR to FIU-IND within 7 working days.**

---

### SECTION 4: INVESTIGATOR REMARKS & ENFORCEMENT ACTIONS
- **Lead Auditor Remarks:** ${investigatorNotes}
- **Remediation Directives:**
  1. Freeze debit transactions on account \`${currentAccount.account_id}\` immediately.
  2. Dispatched automated electronic Form 622-A STR to FIU-IND regulatory portal.
  3. Require beneficial ownership re-declaration before fund release.

---
*Signed digitally by CoCo Governed Compliance Agent v2.4 (Verification Hash: #8f4e2a1b9c704e)*
`;
    } else {
      md = `# BASEL III PRUDENTIAL LIQUIDITY & CAPITAL DEFICIT REPORT
**CONFIDENTIAL // BOARD RISK COMMITTEE & SUPERVISORY AUDIT**
**Entity:** ${currentAccount.entity_name} (${currentAccount.account_id})
**Audit Timestamp:** ${timestamp}

---

### SECTION 1: RATIO DEFICIT ASSESSMENT
- **Liquidity Coverage Ratio (LCR):** **${currentAccount.lcr_pct || 88.4}%** (Statutory BCBS / RBI Minimum: **100.0%** -> **DEFICIT DETECTED**)
- **Capital Adequacy Ratio (CRAR):** **${currentAccount.crar_pct || 13.8}%** (RBI NBFC Scale-Based Regulation Minimum: **15.0%** -> **BREACH**)
- **Tier 1 Capital Ratio:** **${((currentAccount.crar_pct || 13.8) * 0.72).toFixed(1)}%**
- **Estimated High-Quality Liquid Asset (HQLA) Shortfall:** **$1,438,400.00 USD**

---

### SECTION 2: STATUTORY CITATIONS
- **BCBS Basel III LCR Standard (Para 41-45):** Minimum 100% stock of unencumbered HQLA required against 30-day simulated stress net cash outflow.
- **Mandate:** Immediate notification to Department of Supervision (DoS) and activation of Board-Approved Contingency Funding Plan (CFP).

---
*Signed digitally by CoCo Governed Compliance Agent v2.4*
`;
    }

    setGeneratedReport(md);

    // MCP Dispatches
    if (createJiraTicket) {
      const ticketKey = `COMP-${caseId.split('-')[2] || '8921'}`;
      setDispatchedJira(ticketKey);
      if (onDispatchMcpAction) {
        onDispatchMcpAction('JIRA', {
          caseId,
          ticketKey,
          accountId: currentAccount.account_id,
          priority: currentAccount.risk_tier,
          summary: `Automated ${reportType} Filing for ${currentAccount.entity_name}`
        });
      }
    } else {
      setDispatchedJira(null);
    }

    if (notifySlack) {
      setDispatchedSlack(true);
      if (onDispatchMcpAction) {
        onDispatchMcpAction('SLACK', {
          channel: '#risk-triage-officers',
          message: `🚨 Audit Dossier ${caseId} generated for ${currentAccount.account_id}`
        });
      }
    } else {
      setDispatchedSlack(false);
    }
  };

  const handleCopy = () => {
    if (!generatedReport) return;
    navigator.clipboard.writeText(generatedReport);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    if (!generatedReport) return;
    const blob = new Blob([generatedReport], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Audit_Dossier_${targetAccountId}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6">
      {/* Studio Header */}
      <div className="bg-white rounded-xl p-5 border border-slate-200 shadow-xs flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2">
            <h2 className="text-lg font-bold text-slate-900">Audit Report Studio &amp; Regulatory Dossier Generator</h2>
            <span className="px-2.5 py-0.5 rounded-full text-xs font-semibold bg-blue-100 text-blue-800 border border-blue-200">
              CoCo Skill: audit_report_generator
            </span>
          </div>
          <p className="text-xs text-slate-500 mt-1">
            Automates the synthesis of forensic transactional anomalies, Cortex vector regulatory citations, and compliance sign-offs
          </p>
        </div>

        <button
          onClick={handleGenerate}
          className="flex items-center gap-2 px-4 py-2 bg-blue-600 hover:bg-blue-500 text-white rounded-lg text-xs font-semibold transition-colors shadow-sm cursor-pointer"
        >
          <Sparkles className="w-4 h-4" />
          Generate Audit Dossier
        </button>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Left Column: Form & Configuration */}
        <div className="bg-white rounded-xl p-5 border border-slate-200 shadow-xs space-y-5">
          <h3 className="font-semibold text-slate-900 text-sm flex items-center gap-2">
            <Layers className="w-4 h-4 text-blue-600" />
            Dossier Configuration
          </h3>

          <div>
            <label className="block text-xs font-semibold text-slate-700 mb-1.5">
              Target Banking Entity
            </label>
            <select
              value={targetAccountId}
              onChange={(e) => setTargetAccountId(e.target.value)}
              className="w-full px-3 py-2 text-xs border border-slate-300 rounded-lg text-slate-800 focus:outline-none focus:ring-1 focus:ring-blue-500 bg-white"
            >
              {accounts.map((acc) => (
                <option key={acc.account_id} value={acc.account_id}>
                  {acc.account_id} | {acc.entity_name} ({acc.risk_tier})
                </option>
              ))}
            </select>
          </div>

          <div>
            <label className="block text-xs font-semibold text-slate-700 mb-1.5">
              Regulatory Report Template
            </label>
            <div className="space-y-2">
              <label className="flex items-start gap-2.5 p-2.5 rounded-lg border border-slate-200 hover:bg-slate-50 cursor-pointer">
                <input
                  type="radio"
                  name="report_type"
                  value="SAR_STR"
                  checked={reportType === 'SAR_STR'}
                  onChange={() => setReportType('SAR_STR')}
                  className="mt-0.5"
                />
                <div>
                  <div className="text-xs font-semibold text-slate-900">FIU-IND Suspicious Activity Report (SAR/STR)</div>
                  <div className="text-[11px] text-slate-500">RBI Master Direction Section 38 &amp; smurfing/structuring typologies</div>
                </div>
              </label>

              <label className="flex items-start gap-2.5 p-2.5 rounded-lg border border-slate-200 hover:bg-slate-50 cursor-pointer">
                <input
                  type="radio"
                  name="report_type"
                  value="BASEL_LCR"
                  checked={reportType === 'BASEL_LCR'}
                  onChange={() => setReportType('BASEL_LCR')}
                  className="mt-0.5"
                />
                <div>
                  <div className="text-xs font-semibold text-slate-900">Basel III Liquidity Deficit Assessment</div>
                  <div className="text-[11px] text-slate-500">LCR (&lt;100%) and NBFC Scale-Based CRAR (&lt;15%) capital audit</div>
                </div>
              </label>
            </div>
          </div>

          <div>
            <label className="block text-xs font-semibold text-slate-700 mb-1.5">
              Investigator Audit Remarks
            </label>
            <textarea
              rows={3}
              value={investigatorNotes}
              onChange={(e) => setInvestigatorNotes(e.target.value)}
              className="w-full p-2.5 text-xs border border-slate-300 rounded-lg focus:outline-none focus:ring-1 focus:ring-blue-500 text-slate-800"
            />
          </div>

          <div className="pt-2 border-t border-slate-100 space-y-2">
            <span className="block text-xs font-semibold text-slate-700">
              CoCo MCP Automated Actions
            </span>

            <label className="flex items-center gap-2 text-xs text-slate-700 cursor-pointer">
              <input
                type="checkbox"
                checked={createJiraTicket}
                onChange={(e) => setCreateJiraTicket(e.target.checked)}
                className="rounded text-blue-600 focus:ring-blue-500"
              />
              <span className="flex items-center gap-1.5">
                <Ticket className="w-3.5 h-3.5 text-blue-600" />
                Create Jira SAR Investigation Ticket via MCP
              </span>
            </label>

            <label className="flex items-center gap-2 text-xs text-slate-700 cursor-pointer">
              <input
                type="checkbox"
                checked={notifySlack}
                onChange={(e) => setNotifySlack(e.target.checked)}
                className="rounded text-blue-600 focus:ring-blue-500"
              />
              <span className="flex items-center gap-1.5">
                <Bell className="w-3.5 h-3.5 text-emerald-600" />
                Notify <code className="bg-slate-100 px-1 rounded text-slate-800 font-mono">#risk-triage-officers</code> via Slack MCP
              </span>
            </label>
          </div>

          <button
            onClick={handleGenerate}
            className="w-full py-2 bg-slate-900 hover:bg-slate-800 text-white rounded-lg text-xs font-semibold transition-colors flex items-center justify-center gap-1.5 cursor-pointer"
          >
            <Sparkles className="w-3.5 h-3.5" />
            Synthesize Dossier
          </button>
        </div>

        {/* Right 2 Columns: Dossier Document View */}
        <div className="lg:col-span-2 bg-white rounded-xl border border-slate-200 shadow-xs flex flex-col min-h-[500px]">
          <div className="p-4 border-b border-slate-200 flex flex-wrap items-center justify-between gap-2 bg-slate-50">
            <div className="flex items-center gap-2">
              <FileText className="w-4 h-4 text-blue-600" />
              <h3 className="font-semibold text-slate-900 text-xs">
                {generatedReport ? 'Generated Statutory Audit Document' : 'Document Preview Workspace'}
              </h3>
            </div>

            {generatedReport && (
              <div className="flex items-center gap-2">
                <button
                  onClick={handleCopy}
                  className="flex items-center gap-1 px-2.5 py-1 bg-white hover:bg-slate-100 border border-slate-200 rounded text-slate-700 text-xs font-medium transition-colors cursor-pointer"
                >
                  {copied ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5" />}
                  {copied ? 'Copied' : 'Copy'}
                </button>
                <button
                  onClick={handleDownload}
                  className="flex items-center gap-1 px-2.5 py-1 bg-blue-600 hover:bg-blue-500 text-white rounded text-xs font-medium transition-colors cursor-pointer"
                >
                  <Download className="w-3.5 h-3.5" />
                  Export .MD
                </button>
              </div>
            )}
          </div>

          {/* MCP Notification Badges */}
          {(dispatchedJira || dispatchedSlack) && (
            <div className="px-4 py-2.5 bg-blue-50/60 border-b border-blue-100 flex flex-wrap items-center gap-3 text-xs">
              {dispatchedJira && (
                <div className="flex items-center gap-1.5 text-blue-800 font-medium">
                  <Ticket className="w-3.5 h-3.5 text-blue-600" />
                  <span>Jira Ticket Created: <strong className="font-mono bg-blue-100 px-1 rounded">{dispatchedJira}</strong></span>
                </div>
              )}
              {dispatchedSlack && (
                <div className="flex items-center gap-1.5 text-emerald-800 font-medium">
                  <Bell className="w-3.5 h-3.5 text-emerald-600" />
                  <span>Slack Broadcast Sent: <strong className="font-mono bg-emerald-100 px-1 rounded">#risk-triage-officers</strong></span>
                </div>
              )}
            </div>
          )}

          {/* Dossier Content */}
          <div className="flex-1 p-5 overflow-y-auto max-h-[600px] text-xs">
            {generatedReport ? (
              <pre className="whitespace-pre-wrap font-sans text-xs leading-relaxed text-slate-800 bg-slate-50/60 p-4 rounded-lg border border-slate-200">
                {generatedReport}
              </pre>
            ) : (
              <div className="h-full flex flex-col items-center justify-center text-center p-8 text-slate-400 space-y-3">
                <div className="w-12 h-12 rounded-xl bg-slate-100 flex items-center justify-center text-slate-400">
                  <FileText className="w-6 h-6" />
                </div>
                <div>
                  <h4 className="font-semibold text-slate-700 text-sm">No Audit Dossier Generated Yet</h4>
                  <p className="text-xs text-slate-500 max-w-sm mt-1">
                    Select a banking entity and report template on the left, then click <strong>"Synthesize Dossier"</strong> to generate a regulatory compliance report.
                  </p>
                </div>
                <button
                  onClick={handleGenerate}
                  className="px-3 py-1.5 text-xs bg-slate-900 text-white rounded-lg hover:bg-slate-800 transition-colors font-medium cursor-pointer"
                >
                  Generate Sample SAR for ACC-8921-CORP
                </button>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};
